services:
  postgres:
    image: postgres:16.2-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: sqcf
      POSTGRES_HOST_AUTH_METHOD: trust